### ISSUE TITLE
BE 프로젝트 초기 설정

### ISSUE THREAD

**Issue by gchoi96** [boostcampwm-2022/WEB26-RunWithMe#1]
### 배경

- 프로젝트 초기 설정

### 목적

- 프로젝트 초기 설정

## 작업 목록

- [x] Nest.js 설치 및 적용

## 주의 사항

- 작업에 대해 주의사항이 있다면 적어주세요.

**Comment by claycat** [comment]
![스크린샷 2022-12-15 오후 5 18 27](https://user-images.githubusercontent.com/53655119/207808860-fb8be375-c7fc-41ec-9e80-55e25793156c.png)
![스크린샷 2022-12-15 오후 5 19 03](https://user-images.githubusercontent.com/53655119/207808869-93dbd80a-e9be-49bb-b4b8-89945eb7bf83.png)
![스크린샷 2022-12-15 오후 5 19 28](https://user-images.githubusercontent.com/53655119/207808873-9de904f4-486a-4865-b2e1-253a9b5485ed.png)
![스크린샷 2022-12-15 오후 5 19 53](https://user-images.githubusercontent.com/53655119/207808877-eb84c724-6be4-4365-a302-a55b3ec99389.png)
