### ISSUE TITLE
feat: Mock data 생성하기

### ISSUE THREAD

**Issue by claycat** [boostcampwm-2022/WEB26-RunWithMe#112]
### 피처 개요

- 조금 더 고도화된 목데이터 생성 및 저장

### 피처 설명

- 목표 : 3천개의 코스 데이터, 1만개의 모집 데이터
- 어떻게 추가할 것인지?
  - axios 를 통해 직접 API를 찔러서 데이터를 추가
     - 오래 걸릴 것 같음
  - 쿼리를 작성해서 직접 workbench 에서 추가  
     - 실행자체는 빠를듯
     - 하지만 목록을 만들때 user_recruit 테이블에 따로 업데이트가 필요함 귀찮음 

### 체크리스트

- 코스 데이터 생성 
- 모집 데이터 생성 
- 주의: 순서가 지켜져야 함 (foreign key constraint)

**Comment by June1010** [comment]
이거 마이그레이션 이슈도 있는거 같아서 저랑 같이 할까요?? syncrhonize 옵션 때문에 데이터 날라갈 수도 있어서요...

**Comment by claycat** [comment]
지금 봤네요
이거 오늘 테스트페이지 만들어서 axios로 요청 날려봤는데 잘 안되요ㅠ
![image](https://user-images.githubusercontent.com/53655119/204100349-8785d667-8dbf-43ed-93eb-31bef717d98f.png)
대충 요런 느낌으로 날렸고 코드는 feat/mockdata 브랜치에 있읍니다

**Comment by claycat** [comment]
낼 같이 한번 보시죠
