### ISSUE TITLE
회원가입 API 구현 

### ISSUE THREAD

**Issue by pushedrumex** [boostcampwm-2022/WEB26-RunWithMe#12]
### 배경

- 회원가입 API를 구현한다

### 목적

- 회원가입 API를 구현한다

## 작업 목록

- [x] user module, user.service, user.repository 생성
- [x] db 연동

## 주의 사항

- EntityRepository를 사용해서 Reporitory를 분리하여 구현하려고 했지만 EntityRepository는 이제 사용이 불가능하다고 합니다. 일단 user.service에서 모두 작업했습니다.

**Comment by June1010** [comment]
맞습니다. 그래서 커스텀 레포지터리를 생성해서 작업을 해야 하는데, 그 부분은 제가 나중에 추가하도록 할게요.

**Comment by pushedrumex** [comment]
> 맞습니다. 그래서 커스텀 레포지터리를 생성해서 작업을 해야 하는데, 그 부분은 제가 나중에 추가하도록 할게요.

네 알겠습니다!
